package com.mephys.attic.document;

enum DocumentType {

	ID_CARD, PASSPORT, DRIVING_LICENCE, RESIDENCE_PERMIT, HEALTH_CARD, INSURANCE, BIRTH_CERTIFICATE,
	MARRIAGE_CERTIFICATE, VACCINATION_RECORD, DIPLOMA, CONTRACT, OTHER

}
